# Generated by Django 4.2.7 on 2023-12-01 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d6d1c76a-e4d1-4aa3-af0f-5c58e3ff2b0b'), primary_key=True, serialize=False),
        ),
    ]
