# Generated by Django 4.2.7 on 2023-12-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_create_time_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17d05d8f-9031-496b-945a-86aab30b4fe5'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('17d05d8f-9031-496b-945a-86aab30b4fe5'), primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4)),
                ('verify_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=13)),
                ('expiration_time', models.DateTimeField()),
                ('is_confirmation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='verify_code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
