# Generated by Django 4.2.7 on 2023-12-01 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_userconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b64ea16e-8eda-4c23-8710-13364241e424'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b64ea16e-8eda-4c23-8710-13364241e424'), primary_key=True, serialize=False),
        ),
    ]
