# Generated by Django 4.2.7 on 2023-12-04 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_auth_status_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code_verified', 'code_verified'), ('done', 'done'), ('photo_step', 'photo_step')], default='new', max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46b40b42-133a-4f61-9ae4-f0de069edc1b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46b40b42-133a-4f61-9ae4-f0de069edc1b'), primary_key=True, serialize=False),
        ),
    ]
