# Generated by Django 4.2.7 on 2023-12-13 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id_alter_userconfirmation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c44e38f-a219-4ec3-b640-deb72ec3d235'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c44e38f-a219-4ec3-b640-deb72ec3d235'), primary_key=True, serialize=False),
        ),
    ]
