# Generated by Django 4.2.7 on 2023-12-13 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False),
        ),
    ]
