# Generated by Django 4.2.7 on 2023-12-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('83048bbb-648f-4fac-9c6b-d6b0b89bc870'), primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('post', models.ManyToManyField(related_name='saves', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
