# Generated by Django 4.2.7 on 2023-12-15 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_id_alter_commentlike_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e027a9b2-6ca3-4c17-bc0a-1a5b6a4d42fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e027a9b2-6ca3-4c17-bc0a-1a5b6a4d42fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e027a9b2-6ca3-4c17-bc0a-1a5b6a4d42fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e027a9b2-6ca3-4c17-bc0a-1a5b6a4d42fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savepost',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e027a9b2-6ca3-4c17-bc0a-1a5b6a4d42fa'), primary_key=True, serialize=False),
        ),
    ]
